name: coverage

on: [push, pull_request]
jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined

    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate code coverage
        run: |
          cargo +nightly tarpaulin --workspace --exclude zexcavator-lib zexcavator-cli --no-fail-fast --timeout 480 --out xml --output-dir resources -- --nocapture

      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: "resources/cobertura.xml"
          badge: true
          format: "markdown"
          output: "both"

      - uses: jwalton/gh-find-current-pr@v1
        if: github.event_name == 'pull_request'
        id: finder

      - name: Add Coverage PR Comment
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ steps.finder.outputs.pr }}
          header: "Code Coverage Report"
          recreate: true
          path: code-coverage-results.md
